### ISSUE TITLE
mc in mc

### ISSUE THREAD

**Issue by Withererik** [MCHPR/MCHPRS#164]
what version and how to download old version of mchprs is for minecraft in minecraft

**Comment by AL1L** [comment]
"A Minecraft 1.20.4 creative server built for redstone."

https://github.com/MCHPR/MCHPRS/releases

**Comment by JeremyStarTM** [comment]
The MC1.18.2 version of MCHPRS is [v0.4](https://github.com/MCHPR/MCHPRS/releases/tag/v0.4).
For the world download see the description of [sammyuri's video](https://youtube.com/watch?v=-BP7DhHTU-I)

**Comment by Withererik** [comment]
what about functional world download

**Comment by JeremyStarTM** [comment]
It would be nice if you could show a little bit of respect towards me. You are asking this question in a place where it doesn't belong, someone humble helps you anyway and then you leave that comment? Please do better.

To answer your question: I didn't notice the pinned comment where sammyuri mentioned that the world download is broken due to content thieves. Either you have to ask them or find the issue yourself.

**Comment by Withererik** [comment]
Yeah sry for that, im very bad at english so thats why i send you like few words, with more words its kinda hard to understand.
Srry for bad respect.

I got mim from sammy but thx for correct mchprs

**Comment by JeremyStarTM** [comment]
No problem. Have a great day (and don't forget to close the issue) :)
